version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: testdatabase
      POSTGRES_INITDB_ARGS: "--auth-local=md5 --auth-host=md5"
    ports:
      - "5433:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  express-app:
    image: node:latest
    working_dir: /app
    volumes:
      - ./:/app
      - ./package.json:/app/package.json
    command: npm run start
    ports:
      - "3030:3030"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/testdatabase
